var Bank = [
  "Payment Method",
  "Bank Aceh Syariah",
  "Bank Aladin Syariah",
  "Bank Allo Indonesia",
  "Bank Amar Indonesia",
  "Bank ANZ Indonesia",
  "Bank Artha Graha Internasional",
  "Bank Banten",
  "Bank BCA Syariah",
  "Bank Bengkulu",
  "Bank BJB",
  "Bank BJB Syariah",
  "Bank BNP Paribas Indonesia",
  "Bank BPD Bali",
  "Bank BPD DIY",
  "Bank BRK Syariah",
  "Bank BSG",
  "Bank BTPN",
  "Bank BTPN Syariah",
  "Bank Bumi Arta",
  "Bank Capital Indonesia",
  "Bank Central Asia",
  "Bank China Construction Bank Indonesia",
  "Bank CIMB Niaga",
  "Bank Commonwealth",
  "Bank CTBC Indonesia",
  "Bank Danamon Indonesia",
  "Bank DBS Indonesia",
  "Bank Digital BCA",
  "Bank DKI",
  "Bank Ganesha",
  "Bank HSBC Indonesia",
  "Bank IBK Indonesia",
  "Bank ICBC Indonesia",
  "Bank Ina Perdana",
  "Bank Index Selindo",
  "Bank Jago",
  "Bank Jambi",
  "Bank Jasa Jakarta",
  "Bank Jateng",
  "Bank Jatim",
  "Bank J Trust Indonesia",
  "Bank Kalbar",
  "Bank Kalsel",
  "Bank Kalteng",
  "Bank Kaltimtara",
  "Bank KB Bukopin",
  "Bank KB Bukopin Syariah",
  "Bank KEB Hana Indonesia",
  "Bank Krom Indonesia",
  "Bank Lampung",
  "Bank Maluku Malut",
  "Bank Mandiri",
  "Bank Mandiri Taspen",
  "Bank Maspion",
  "Bank Mayapada Internasional",
  "Bank Maybank Indonesia",
  "Bank Mayora",
  "Bank Mega",
  "Bank Mega Syariah",
  "Bank Mestika Dharma",
  "Bank Mizuho Indonesia",
  "Bank MNC Internasional",
  "Bank Muamalat Indonesia",
  "Bank Multiarta Sentosa",
  "Bank Nagari",
  "Bank Nationalnobu",
  "Bank Negara Indonesia",
  "Bank Neo Commerce",
  "Bank NTB Syariah",
  "Bank NTT",
  "Bank OCBC NISP",
  "Bank of India Indonesia",
  "Bank Oke Indonesia",
  "Bank Panin",
  "Bank Panin Dubai Syariah",
  "Bank Papua",
  "Bank Permata",
  "Bank QNB Indonesia",
  "Bank Rakyat Indonesia",
  "Bank Raya Indonesia",
  "Bank Resona Perdania",
  "Bank Sahabat Sampoerna",
  "Bank SBI Indonesia",
  "Bank Seabank Indonesia",
  "Bank Shinhan Indonesia",
  "Bank Sinarmas",
  "Bank Sulselbar",
  "Bank Sulteng",
  "Bank Sultra",
  "Bank Sumsel Babel",
  "Bank Sumut",
  "Bank Super Indonesia",
  "Bank Syariah Indonesia",
  "Bank Tabungan Negara",
  "Bank UOB Indonesia",
  "Bank Victoria Internasional",
  "Bank Victoria Syariah",
  "Bank Woori Saudara"
];

var EMoney = [
  "Payment Method",
  "BBM Money",
  "Bluepay",
  "Brizzi",
  "BSB Cash",
  "Dana",
  "DokuPay",
  "Dompetku",
  "Dooet",
  "DUWIT",
  "Ezeelink",
  "FinnChannel",
  "Flazz",
  "Flexy Cash",
  "GoPay",
  "Gudang Voucher",
  "iSaku",
  "iVas Card",
  "JakCard",
  "JakOne",
  "KasPro",
  "LinkAja",
  "M-Bayar",
  "Mandiri E-Cash",
  "Mandiri E-Money",
  "Mega Cash",
  "Mega Virtual",
  "MYNT E-money",
  "Nobu E-Money",
  "OttoCash",
  "OVO Cash",
  "Paytren",
  "Sakuku dan Flazz",
  "ShopeePay",
  "Simas E-Money",
  "Skye Mobile Money",
  "SkyeCard",
  "Speed Cash",
  "T-Bank",
  "T-Cash",
  "Tap Izy",
  "TapCash",
  "TrueMoney",
  "Uangku",
  "UnikQu",
  "XL Tunai",
];

var AllPaymentMethod = [
  "Payment Method",
  "BBM Money",
  "Bluepay",
  "Brizzi",
  "BSB Cash",
  "Dana",
  "DokuPay",
  "Dompetku",
  "Dooet",
  "DUWIT",
  "Ezeelink",
  "FinnChannel",
  "Flazz",
  "Flexy Cash",
  "GoPay",
  "Gudang Voucher",
  "iSaku",
  "iVas Card",
  "JakCard",
  "JakOne",
  "KasPro",
  "LinkAja",
  "M-Bayar",
  "Mandiri E-Cash",
  "Mandiri E-Money",
  "Mega Cash",
  "Mega Virtual",
  "MYNT E-money",
  "Nobu E-Money",
  "OttoCash",
  "OVO Cash",
  "Paytren",
  "Sakuku dan Flazz",
  "ShopeePay",
  "Simas E-Money",
  "Skye Mobile Money",
  "SkyeCard",
  "Speed Cash",
  "T-Bank",
  "T-Cash",
  "Tap Izy",
  "TapCash",
  "TrueMoney",
  "Uangku",
  "UnikQu",
  "XL Tunai",
  "Bank Aceh Syariah",
  "Bank Aladin Syariah",
  "Bank Allo Indonesia",
  "Bank Amar Indonesia",
  "Bank ANZ Indonesia",
  "Bank Artha Graha Internasional",
  "Bank Banten",
  "Bank BCA Syariah",
  "Bank Bengkulu",
  "Bank BJB",
  "Bank BJB Syariah",
  "Bank BNP Paribas Indonesia",
  "Bank BPD Bali",
  "Bank BPD DIY",
  "Bank BRK Syariah",
  "Bank BSG",
  "Bank BTPN",
  "Bank BTPN Syariah",
  "Bank Bumi Arta",
  "Bank Capital Indonesia",
  "Bank Central Asia",
  "Bank China Construction Bank Indonesia",
  "Bank CIMB Niaga",
  "Bank Commonwealth",
  "Bank CTBC Indonesia",
  "Bank Danamon Indonesia",
  "Bank DBS Indonesia",
  "Bank Digital BCA",
  "Bank DKI",
  "Bank Ganesha",
  "Bank HSBC Indonesia",
  "Bank IBK Indonesia",
  "Bank ICBC Indonesia",
  "Bank Ina Perdana",
  "Bank Index Selindo",
  "Bank Jago",
  "Bank Jambi",
  "Bank Jasa Jakarta",
  "Bank Jateng",
  "Bank Jatim",
  "Bank J Trust Indonesia",
  "Bank Kalbar",
  "Bank Kalsel",
  "Bank Kalteng",
  "Bank Kaltimtara",
  "Bank KB Bukopin",
  "Bank KB Bukopin Syariah",
  "Bank KEB Hana Indonesia",
  "Bank Krom Indonesia",
  "Bank Lampung",
  "Bank Maluku Malut",
  "Bank Mandiri",
  "Bank Mandiri Taspen",
  "Bank Maspion",
  "Bank Mayapada Internasional",
  "Bank Maybank Indonesia",
  "Bank Mayora",
  "Bank Mega",
  "Bank Mega Syariah",
  "Bank Mestika Dharma",
  "Bank Mizuho Indonesia",
  "Bank MNC Internasional",
  "Bank Muamalat Indonesia",
  "Bank Multiarta Sentosa",
  "Bank Nagari",
  "Bank Nationalnobu",
  "Bank Negara Indonesia",
  "Bank Neo Commerce",
  "Bank NTB Syariah",
  "Bank NTT",
  "Bank OCBC NISP",
  "Bank of India Indonesia",
  "Bank Oke Indonesia",
  "Bank Panin",
  "Bank Panin Dubai Syariah",
  "Bank Papua",
  "Bank Permata",
  "Bank QNB Indonesia",
  "Bank Rakyat Indonesia",
  "Bank Raya Indonesia",
  "Bank Resona Perdania",
  "Bank Sahabat Sampoerna",
  "Bank SBI Indonesia",
  "Bank Seabank Indonesia",
  "Bank Shinhan Indonesia",
  "Bank Sinarmas",
  "Bank Sulselbar",
  "Bank Sulteng",
  "Bank Sultra",
  "Bank Sumsel Babel",
  "Bank Sumut",
  "Bank Super Indonesia",
  "Bank Syariah Indonesia",
  "Bank Tabungan Negara",
  "Bank UOB Indonesia",
  "Bank Victoria Internasional",
  "Bank Victoria Syariah",
  "Bank Woori Saudara"
];
